[project]
name = "acoustic-camera"
version = "1.0.0"
description = "This project uses Acoular to implement an acoustic camera for the miniDSP UMA-16 microphone array, with optional integration of transformer model."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "acoular==25.03",
    "bokeh==3.5.2",
    "opencv-python==4.11.0.86",
    "flask==3.1.0",
    "h5py==3.11.0",
    "numpy==1.26.4",
    "sounddevice==0.5.0",
    "scipy==1.14.0",
    "traits==6.4.3",
    "tensorflow==2.18.0",
]
